version: "3"
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask-container
    restart: on-failure
    ports:
      - 5005:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: db-container
    ports:
      - 5440:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres-volume:
